//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using Cap.Generales.BusinessObjects.Object;

namespace Escul.Module.BusinessObjects
{
    [DefaultClassOptions]
    public partial class Parametros : PObject
    {
        public Parametros(DevExpress.Xpo.Session session)
            : base(session)
        {
        }
    }
}
